/**
 * Metrics Service
 * 
 * Handles fetching instance metrics and scaling decisions
 * All functions strictly follow the OpenAPI specification
 */

import axiosInstance from '../api/axiosInstance';
import {
    Metric,
    ScalingDecision,
    MetricsResponse,
    ScalingDecisionsResponse,
} from '../types/metrics.types';

/**
 * Fetch metrics for a specific instance
 * 
 * @param instanceId - AWS instance ID
 * @param limit - Maximum number of metrics to return (default: 100)
 * @returns Array of Metric objects sorted by timestamp
 * @throws Error if instance not found or unauthorized
 */
export const getMetrics = async (instanceId: string, limit: number = 100): Promise<Metric[]> => {
    try {
        const response = await axiosInstance.get<MetricsResponse>(
            `/api/metrics/${instanceId}`,
            { params: { limit } }
        );
        return response.data.metrics;
    } catch (error: any) {  
        const errorMessage = error.response?.data?.error || 'Failed to fetch metrics.';
        throw new Error(errorMessage);
    }
};

/**
 * Fetch scaling decisions for a specific instance
 * 
 * Scaling decisions are autoscaling recommendations generated by the backend
 * based on IQR analysis or immediate threshold triggers
 * 
 * @param instanceId - AWS instance ID
 * @param limit - Maximum number of decisions to return (default: 50)
 * @returns Array of ScalingDecision objects
 * @throws Error if instance not found or unauthorized
 */
export const getScalingDecisions = async (instanceId: string, limit: number = 50): Promise<ScalingDecision[]> => {
    try {
        const response = await axiosInstance.get<ScalingDecisionsResponse>(
            `/api/metrics/decisions/${instanceId}`,
            { params: { limit } }
        );
        return response.data.decisions;
    } catch (error: any) {
        const errorMessage = error.response?.data?.error || 'Failed to fetch scaling decisions.';
        throw new Error(errorMessage);
    }
};
